### PR TITLE
THERE

### PR DESCRIPTION
**Pull request by BlueNexus**

### CODE REVIEW

**Comment by Zuhayr** [comment]
If you're using the Bay Travis.yml file then it will fail if you commit a .int file that has changed in any way from the one in the main repo.

**Comment by BlueNexus** [comment]
@zuhayr I know. I'm trying to get the .int file back to the way it's supposed to be.

**Comment by JakeDaBoss** [comment]
@Zuhayr would replacing the file with the one in the bay repo fix it?

**Comment by Zuhayr** [comment]
It should, yes.

**Comment by JakeDaBoss** [comment]
I'll go ahead and do that.

**Pull request closed without merging**
